name: yolo_casino_task
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.0.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.1
  bloc_test: ^9.0.2
  mockito: ^5.0.15
  mocktail: ^0.2.0

flutter:
  uses-material-design: true


  assets:
    - assets/
